openapi: 3.0.0
info:
  title: My API
  version: 1.0.0

servers:
  - url: http://{environment}/api
    description: API server
    variables:
      environment:
        default: localhost:5000
        enum:
          - localhost:5000
          - mydomain.com


paths: {}        # will be merged
components:
  schemas: {}     # will be extended
  securitySchemes: {}
